// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"

import mock "github.com/stretchr/testify/mock"
import model "github.com/rockspoon/rs.cor.device-model/model"

// DeviceMS is an autogenerated mock type for the DeviceMS type
type DeviceMS struct {
	mock.Mock
}

// GetDefaultPrinter provides a mock function with given fields: ctx
func (_m *DeviceMS) GetDefaultPrinter(ctx context.Context) (*model.Printer, error) {
	ret := _m.Called(ctx)

	var r0 *model.Printer
	if rf, ok := ret.Get(0).(func(context.Context) *model.Printer); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Printer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
